name: RM2PT CodeGenerator Rm2doc

on: [push]
  
jobs:
   
  RM2PT-Package:
    name: RM2PT Compile and Package
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        architecture: x64
        
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Staging
      run: |
        mkdir -p staging
        cp -r com.rm2pt.generator.rm2doc.updatesite/target/*.zip staging

    - uses: actions/upload-artifact@v1
      if: true
      with:
        name: RM2PT-UpdateSite
        path: staging/com.rm2pt.generator.rm2doc.updatesite-1.0.0-SNAPSHOT.zip         
          
        
  Deployment-Release:
    name: Deploy Release
    needs: RM2PT-Package
    if: true
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v1.0.0
          release_name: RM2PT CodeGenerator Rm2doc v1.0.0
          commitish: master
          body: |
            RM2PT CodeGenerator Rm2doc, which includes features as follows:
            - XX
            - XX
          draft: true
          prerelease: false
            
      - name: Download UpdateSite
        uses: actions/download-artifact@v1
        with:
           name: RM2PT-UpdateSite
           path: Release
         
      - uses: geekyeggo/delete-artifact@v1
        with:
           name: RM2PT-UpdateSite    

      - name: Upload UpdateSite Release
        id: upload-release-updatesite
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_name: com.rm2pt.generator.springboot.updatesite-1.0.0-SNAPSHOT.zip
          asset_path: Release/com.rm2pt.generator.springboot.updatesite-1.0.0-SNAPSHOT.zip
          asset_content_type: application/zip
